import { index, integer, primaryKey, real, sqliteTable, text, unique } from "drizzle-orm/sqlite-core";

export const teamRefs = sqliteTable("team_refs", {
  id: text("id").primaryKey(), slug: text("slug").notNull(), name: text("name").notNull(),
  ccSettings: text("cc_settings", { mode: "json" }).$type<Record<string, unknown>>().notNull(),
  settings: text("settings", { mode: "json" }).$type<Record<string, unknown>>().notNull(), syncedAt: integer("synced_at", { mode: "timestamp" }).notNull(),
});
export const teamMembers = sqliteTable("team_members", { teamId: text("team_id").notNull(), userId: text("user_id").notNull(), role: text("role").notNull() }, (t) => [primaryKey({ columns: [t.teamId, t.userId] })]);
export const sprints = sqliteTable("sprints", { id: text("id").primaryKey(), teamId: text("team_id").notNull(), name: text("name").notNull(), goal: text("goal"), startsOn: text("starts_on").notNull(), endsOn: text("ends_on").notNull(), status: text("status").notNull(), capacityMinutes: integer("capacity_minutes"), approvedBy: text("approved_by"), approvedAt: integer("approved_at", { mode: "timestamp" }), createdBy: text("created_by").notNull(), createdAt: integer("created_at", { mode: "timestamp" }), updatedAt: integer("updated_at", { mode: "timestamp" }) }, (t) => [index("idx_sprint_team").on(t.teamId)]);
export const sprintPlans = sqliteTable("sprint_plans", { id: text("id").primaryKey(), teamId: text("team_id").notNull(), sprintId: text("sprint_id"), kind: text("kind").notNull(), promptInput: text("prompt_input", { mode: "json" }).$type<Record<string, unknown>>().notNull(), proposal: text("proposal", { mode: "json" }).$type<Record<string, unknown>>().notNull(), humanEdits: text("human_edits", { mode: "json" }).$type<Record<string, unknown>>(), status: text("status").notNull(), decidedBy: text("decided_by"), decidedAt: integer("decided_at", { mode: "timestamp" }), createdAt: integer("created_at", { mode: "timestamp" }) });
export const taskReviews = sqliteTable("task_reviews", { id: text("id").primaryKey(), teamId: text("team_id").notNull(), reviewDate: text("review_date").notNull(), ranAt: integer("ran_at", { mode: "timestamp" }).notNull(), slot: text("slot").notNull(), status: text("status").notNull(), finishedAt: integer("finished_at", { mode: "timestamp" }), summary: text("summary", { mode: "json" }).$type<Record<string, unknown>>().notNull() }, (t) => [unique("uniq_team_review_slot").on(t.teamId, t.reviewDate, t.slot)]);
export const taskReviewItems = sqliteTable("task_review_items", { id: text("id").primaryKey(), reviewId: text("review_id").notNull(), taskId: text("task_id").notNull(), score: real("score").notNull(), evidence: text("evidence", { mode: "json" }).$type<Record<string, unknown>>().notNull(), evidenceFingerprint: text("evidence_fingerprint").notNull(), verdict: text("verdict").notNull(), decision: text("decision"), decidedBy: text("decided_by"), decidedAt: integer("decided_at", { mode: "timestamp" }) });
export const taskDelays = sqliteTable("task_delays", { taskId: text("task_id").notNull(), detectedOn: text("detected_on").notNull(), daysLate: integer("days_late").notNull(), reportedAt: integer("reported_at", { mode: "timestamp" }) }, (t) => [primaryKey({ columns: [t.taskId, t.detectedOn] })]);
export const memberAvailability = sqliteTable("member_availability", { id: text("id").primaryKey(), teamId: text("team_id").notNull(), userId: text("user_id").notNull(), date: text("date").notNull(), availableMinutes: integer("available_minutes").notNull(), note: text("note") });
export const workLogs = sqliteTable("work_logs", { id: text("id").primaryKey(), taskId: text("task_id").notNull(), userId: text("user_id").notNull(), minutes: integer("minutes").notNull(), loggedAt: integer("logged_at", { mode: "timestamp" }).notNull(), note: text("note") });
export const sprintRetros = sqliteTable("sprint_retros", { id: text("id").primaryKey(), sprintId: text("sprint_id").notNull(), teamId: text("team_id").notNull(), summary: text("summary", { mode: "json" }).$type<Record<string, unknown>>().notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const teamMetricsDaily = sqliteTable("team_metrics_daily", { teamId: text("team_id").notNull(), date: text("date").notNull(), metrics: text("metrics", { mode: "json" }).$type<Record<string, unknown>>().notNull() }, (t) => [primaryKey({ columns: [t.teamId, t.date] })]);
export const sprintMetrics = sqliteTable("sprint_metrics", { sprintId: text("sprint_id").primaryKey(), metrics: text("metrics", { mode: "json" }).$type<Record<string, unknown>>().notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() });
export const adjustmentProposals = sqliteTable("adjustment_proposals", { id: text("id").primaryKey(), teamId: text("team_id").notNull(), proposal: text("proposal", { mode: "json" }).$type<Record<string, unknown>>().notNull(), status: text("status").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const ganttSnapshots = sqliteTable("gantt_snapshots", { id: text("id").primaryKey(), teamId: text("team_id").notNull(), data: text("data", { mode: "json" }).$type<Record<string, unknown>>().notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
